import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Link from "next/link";
import './a.sass'

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div className='flex justify-center align-middle bg-blue-600'>
            <Link className='p-3' href={'/kira'}>Posts</Link>
            <Link className='p-3' href={'/makima'}>Makima</Link>
        </div>
        {children}
        </body>
        </html>
    );
}
